version: '3.9'
services:
  earthquake-backend-db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5555:5432'
    volumes:
      - earthquake-db-data-v1:/var/lib/postgresql/data

volumes:
  earthquake-db-data-v1:

